apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: server
          servicePort: 3000
status:
  loadBalancer: {}
