apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.expose: "true"
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.service.expose: "true"
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: server
    spec:
      containers:
      - image: gcr.io/apesounds/server
        name: server
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
