apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: sms
  name: sms
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: sms
    spec:
      containers:
      - image: gcr.io/apesounds/sms
        name: sms
        ports:
        - containerPort: 50051
        resources: {}
      restartPolicy: Always
status: {}
