/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

const jspb = require('google-protobuf');

const goog = jspb;
const global = Function('return this')();

const google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');

goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.hackgt6.GroupInvite', null, global);
goog.exportSymbol('proto.hackgt6.InviteResponse', null, global);
goog.exportSymbol('proto.hackgt6.InviteToken', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.hackgt6.GroupInvite = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.hackgt6.GroupInvite.repeatedFields_, null);
};
goog.inherits(proto.hackgt6.GroupInvite, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.hackgt6.GroupInvite.displayName = 'proto.hackgt6.GroupInvite';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.hackgt6.GroupInvite.repeatedFields_ = [2];


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
  proto.hackgt6.GroupInvite.prototype.toObject = function (opt_includeInstance) {
    return proto.hackgt6.GroupInvite.toObject(opt_includeInstance, this);
  };


  /**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.hackgt6.GroupInvite} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
  proto.hackgt6.GroupInvite.toObject = function (includeInstance, msg) {
    let f; const
      obj = {
        body: jspb.Message.getFieldWithDefault(msg, 1, ''),
        invitePhoneNumList: jspb.Message.getRepeatedField(msg, 2),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.hackgt6.GroupInvite}
 */
proto.hackgt6.GroupInvite.deserializeBinary = function (bytes) {
  const reader = new jspb.BinaryReader(bytes);
  const msg = new proto.hackgt6.GroupInvite();
  return proto.hackgt6.GroupInvite.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.hackgt6.GroupInvite} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.hackgt6.GroupInvite}
 */
proto.hackgt6.GroupInvite.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    const field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setBody(value);
        break;
      case 2:
        var value = /** @type {string} */ (reader.readString());
        msg.addInvitePhoneNum(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.hackgt6.GroupInvite.prototype.serializeBinary = function () {
  const writer = new jspb.BinaryWriter();
  proto.hackgt6.GroupInvite.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.hackgt6.GroupInvite} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hackgt6.GroupInvite.serializeBinaryToWriter = function (message, writer) {
  let f;
  f = message.getBody();
  if (f.length > 0) {
    writer.writeString(
      1,
      f,
    );
  }
  f = message.getInvitePhoneNumList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f,
    );
  }
};


/**
 * optional string body = 1;
 * @return {string}
 */
proto.hackgt6.GroupInvite.prototype.getBody = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''));
};


/** @param {string} value */
proto.hackgt6.GroupInvite.prototype.setBody = function (value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated string invite_phone_num = 2;
 * @return {!Array<string>}
 */
proto.hackgt6.GroupInvite.prototype.getInvitePhoneNumList = function () {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/** @param {!Array<string>} value */
proto.hackgt6.GroupInvite.prototype.setInvitePhoneNumList = function (value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.hackgt6.GroupInvite.prototype.addInvitePhoneNum = function (value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.hackgt6.GroupInvite.prototype.clearInvitePhoneNumList = function () {
  this.setInvitePhoneNumList([]);
};


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.hackgt6.InviteToken = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.hackgt6.InviteToken, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.hackgt6.InviteToken.displayName = 'proto.hackgt6.InviteToken';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
  proto.hackgt6.InviteToken.prototype.toObject = function (opt_includeInstance) {
    return proto.hackgt6.InviteToken.toObject(opt_includeInstance, this);
  };


  /**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.hackgt6.InviteToken} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
  proto.hackgt6.InviteToken.toObject = function (includeInstance, msg) {
    let f; const
      obj = {
        tokenId: jspb.Message.getFieldWithDefault(msg, 1, ''),
        phoneNumber: jspb.Message.getFieldWithDefault(msg, 2, ''),
        expiration: (f = msg.getExpiration()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.hackgt6.InviteToken}
 */
proto.hackgt6.InviteToken.deserializeBinary = function (bytes) {
  const reader = new jspb.BinaryReader(bytes);
  const msg = new proto.hackgt6.InviteToken();
  return proto.hackgt6.InviteToken.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.hackgt6.InviteToken} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.hackgt6.InviteToken}
 */
proto.hackgt6.InviteToken.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    const field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setTokenId(value);
        break;
      case 2:
        var value = /** @type {string} */ (reader.readString());
        msg.setPhoneNumber(value);
        break;
      case 3:
        var value = new google_protobuf_timestamp_pb.Timestamp();
        reader.readMessage(value, google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
        msg.setExpiration(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.hackgt6.InviteToken.prototype.serializeBinary = function () {
  const writer = new jspb.BinaryWriter();
  proto.hackgt6.InviteToken.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.hackgt6.InviteToken} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hackgt6.InviteToken.serializeBinaryToWriter = function (message, writer) {
  let f;
  f = message.getTokenId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f,
    );
  }
  f = message.getPhoneNumber();
  if (f.length > 0) {
    writer.writeString(
      2,
      f,
    );
  }
  f = message.getExpiration();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter,
    );
  }
};


/**
 * optional string token_id = 1;
 * @return {string}
 */
proto.hackgt6.InviteToken.prototype.getTokenId = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''));
};


/** @param {string} value */
proto.hackgt6.InviteToken.prototype.setTokenId = function (value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string phone_number = 2;
 * @return {string}
 */
proto.hackgt6.InviteToken.prototype.getPhoneNumber = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ''));
};


/** @param {string} value */
proto.hackgt6.InviteToken.prototype.setPhoneNumber = function (value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional google.protobuf.Timestamp expiration = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.hackgt6.InviteToken.prototype.getExpiration = function () {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.hackgt6.InviteToken.prototype.setExpiration = function (value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.hackgt6.InviteToken.prototype.clearExpiration = function () {
  this.setExpiration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hackgt6.InviteToken.prototype.hasExpiration = function () {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.hackgt6.InviteResponse = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.hackgt6.InviteResponse.repeatedFields_, null);
};
goog.inherits(proto.hackgt6.InviteResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.hackgt6.InviteResponse.displayName = 'proto.hackgt6.InviteResponse';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.hackgt6.InviteResponse.repeatedFields_ = [1];


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
  proto.hackgt6.InviteResponse.prototype.toObject = function (opt_includeInstance) {
    return proto.hackgt6.InviteResponse.toObject(opt_includeInstance, this);
  };


  /**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.hackgt6.InviteResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
  proto.hackgt6.InviteResponse.toObject = function (includeInstance, msg) {
    let f; const
      obj = {
        invitesList: jspb.Message.toObjectList(msg.getInvitesList(),
          proto.hackgt6.InviteToken.toObject, includeInstance),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.hackgt6.InviteResponse}
 */
proto.hackgt6.InviteResponse.deserializeBinary = function (bytes) {
  const reader = new jspb.BinaryReader(bytes);
  const msg = new proto.hackgt6.InviteResponse();
  return proto.hackgt6.InviteResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.hackgt6.InviteResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.hackgt6.InviteResponse}
 */
proto.hackgt6.InviteResponse.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    const field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = new proto.hackgt6.InviteToken();
        reader.readMessage(value, proto.hackgt6.InviteToken.deserializeBinaryFromReader);
        msg.addInvites(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.hackgt6.InviteResponse.prototype.serializeBinary = function () {
  const writer = new jspb.BinaryWriter();
  proto.hackgt6.InviteResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.hackgt6.InviteResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hackgt6.InviteResponse.serializeBinaryToWriter = function (message, writer) {
  let f;
  f = message.getInvitesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.hackgt6.InviteToken.serializeBinaryToWriter,
    );
  }
};


/**
 * repeated InviteToken invites = 1;
 * @return {!Array<!proto.hackgt6.InviteToken>}
 */
proto.hackgt6.InviteResponse.prototype.getInvitesList = function () {
  return /** @type{!Array<!proto.hackgt6.InviteToken>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.hackgt6.InviteToken, 1));
};


/** @param {!Array<!proto.hackgt6.InviteToken>} value */
proto.hackgt6.InviteResponse.prototype.setInvitesList = function (value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.hackgt6.InviteToken=} opt_value
 * @param {number=} opt_index
 * @return {!proto.hackgt6.InviteToken}
 */
proto.hackgt6.InviteResponse.prototype.addInvites = function (opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.hackgt6.InviteToken, opt_index);
};


proto.hackgt6.InviteResponse.prototype.clearInvitesList = function () {
  this.setInvitesList([]);
};


goog.object.extend(exports, proto.hackgt6);
